name: CI
on: 
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main

jobs:

  "validity-Tests":
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install swiftformat
      run: brew install swiftformat
    - name: Run validity
      run: ./scripts/validity.sh .

  "tuxOS-Tests":
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images:
        - swift:5.1
        - swift:5.2
        - swift:5.3
        - swiftlang/swift:nightly-master
    container:
      image: ${{ matrix.images }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: swift test --enable-code-coverage --enable-test-discovery
    - name: Convert coverage files
      run: llvm-cov export -format="lcov" .build/debug/swift-base64-kitPackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Install curl
      if: matrix.images != 'swiftlang/swift:nightly-amazonlinux2'
      run: apt-get update && apt-get install -y curl # required by the codecov action.
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
      with:
        file: info.lcov

  "tuxOS-Performance-Tests":
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images:
        - swift:5.1
        - swift:5.2
        - swift:5.3
        - swiftlang/swift:nightly-master
    container:
      image: ${{ matrix.images }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build & run
      run: swift run -c release

  "tuxOS-Integration-Tests":
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images:
        - swift:5.3
        - swiftlang/swift:nightly-master
    container:
      image: ${{ matrix.images }}
    env:
      MAX_ALLOCS_ALLOWED_base64_decoding: 1000
      MAX_ALLOCS_ALLOWED_base64_encoding: 1000
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: ./run-tests.sh
      working-directory: ./IntegrationTests

  "macOS-Tests":
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        xcodes:
        - 11.2
        - 12
        - 12.1
        - 12.2
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Show all Xcode versions
      run: ls -an /Applications/ | grep Xcode*
    - name: Change Xcode command line tools
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcodes }}.app/Contents/Developer
    - name: SPM Build
      run: swift build
    - name: SPM Tests
      run: swift test --parallel -Xswiftc -DDEBUG
    - name: Xcode Tests
      run: |
        swift package generate-xcodeproj
        xcodebuild -quiet -parallel-testing-enabled YES -scheme swift-base64-kit-Package -enableCodeCoverage YES build test
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash) -t ${{secrets.CODECOV_TOKEN}} -f *.coverage.txt

  "macOS-Performance-Tests":
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        xcodes:
        - 11.2
        - 12
        - 12.1
        - 12.2
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Show all Xcode versions
      run: ls -an /Applications/ | grep Xcode*
    - name: Change Xcode command line tools
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcodes }}.app/Contents/Developer
    - name: Build & run
      run: swift run -c release
